#!/usr/bin/env bash

MINIKUBE_ENV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$MINIKUBE_ENV_DIR/../../../.." && pwd)"

MINIKUBE_PROFILE="${MINIKUBE_PROFILE:-easy-bank-dev}"
MINIKUBE_CPUS="${MINIKUBE_CPUS:-4}"
MINIKUBE_MEMORY="${MINIKUBE_MEMORY:-8192}"
MINIKUBE_DISK_SIZE="${MINIKUBE_DISK_SIZE:-40g}"
K8S_NAMESPACE="${K8S_NAMESPACE:-easy-bank-dev}"
