apiVersion: v1
kind: Service
metadata:
  name: eb-mysql
  namespace: easy-bank-dev
spec:
  type: ClusterIP
  selector:
    app: eb-mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
