apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eb-mysql-data
  namespace: easy-bank-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
